spring:
  profiles:
    include: dev
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/KB?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        connection:
          useUnicode: true
    connection:
      CharSet: utf8
      characterEncoding: utf8
    database-platform: org.hibernate.dialect.MySQL8Dialect
  
        
logging:
  level:
    web: DEBUG
    
frontend:
  url: http://62.169.17.131:3000